version: '3'
services:
  sango-sftp:
    container_name: sango-sftp
    build:
      context: .
      args:
          SSH_MASTER_USER: sango
          SSH_MASTER_PASS: sango
    ports:
      - "2222:22"
    volumes:
      - ./sftp-data/uploaded:/uploads
